/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testForDice(){
        Library testDice = new Library();
        int flips= 20;
        int expectedOutput = flips;
        int[] actualOutput= Library.roll(flips);
        System.out.println(Arrays.toString(actualOutput));
        assertSame("Expred number of flips "+flips,expectedOutput,actualOutput.length);
    }

    @Test public void testForDupes(){
        Library hasDupes = new Library();
        int[] testArrOne = {66, 64, 58, 65, 71, 57, 60,43,233,4213,132,64,23213,213,123};
//        boolean expectedOutput = true;
        boolean actualOutput = Library.containsDuplicates(testArrOne);

        assertTrue("should be true for first set",actualOutput);

        int[] testArrTwo={1,2,3,4,5,6,7,121,1222,2323,6767,878787,785676575,57665765,657657,567};

        assertTrue("should be false no dupes in this one",!Library.containsDuplicates(testArrTwo));

    }

    @Test public void testForAverage(){
        int[] arrayHolder = {1,2,3,4,5,6};
        float expectedOutput = 3.5f;
        float actualOutput = Library.calculateAverage(arrayHolder);
        assertEquals(expectedOutput,actualOutput,0);
    }

    @Test public void testForAverageLowesetWeekly(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57},
                {1,2,3,4,5,6,7}
        };

        int[] expectedOutput = {1,2,3,4,5,6,7};
        int[] actualOutput= Library.averageLowestArray(weeklyMonthTemperatures);

        assertArrayEquals("exprected array should be [1,2,3,4,5,6,7] cause it has the lowest ave",expectedOutput,actualOutput);
    }

    @Test public void testStringTemp(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57},
                {123,4343,4545,5454,34543,43543},
                {1,2,3,4,5,6,7,8,9},
                {12,123,1234,12}
        };
        String expectedOutput="epic";
        String actualOutput = Library.averageTempString(weeklyMonthTemperatures);
        assertEquals("should be epic",expectedOutput,actualOutput);
    }

    @Test public void testTally(){
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = Library.tally(votes);
        System.out.println(winner + " received the most votes!");
        String expected ="Bush received the most votes!";

        assertEquals("SHould be bush as the winner",expected,winner);
    }
}
