/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testForDice(){
        Library testDice = new Library();
        int flips= 20;
        int expectedOutput = flips;
        int[] actualOutput= Library.roll(flips);
        System.out.println(Arrays.toString(actualOutput));
        assertSame("Expred number of flips "+flips,expectedOutput,actualOutput.length);
    }

    @Test public void testForDupes(){
        Library hasDupes = new Library();
        int[] testArrOne = {66, 64, 58, 65, 71, 57, 60,43,233,4213,132,64,23213,213,123};
//        boolean expectedOutput = true;
        boolean actualOutput = Library.containsDuplicates(testArrOne);

        assertTrue("should be true for first set",actualOutput);

        int[] testArrTwo={1,2,3,4,5,6,7,121,1222,2323,6767,878787,785676575,57665765,657657,567};

        assertTrue("should be false no dupes in this one",!Library.containsDuplicates(testArrTwo));

    }

    @Test public void testForAverage(){
        int[] arrayHolder = {1,2,3,4,5,6};
        float expectedOutput = 3.5f;
        float actualOutput = Library.calculateAverage(arrayHolder);
        assertEquals(expectedOutput,actualOutput,0);
    }

    @Test public void testForAverageLowesetWeekly(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57},
                {1,2,3,4,5,6,7}
        };

        int[] expectedOutput = {1,2,3,4,5,6,7};
        int[] actualOutput= Library.averageLowestArray(weeklyMonthTemperatures);

        assertArrayEquals("exprected array should be [1,2,3,4,5,6,7] cause it has the lowest ave",expectedOutput,actualOutput);
    }
}
