/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRestaurantConstructor(){
        Restaurant holder = new Restaurant("Chi's",5,"$$");

        assertSame(5,holder.stars);



    }

    @Test public void testToString(){
        Restaurant holder = new Restaurant("Chi's",5,"$$");

        System.out.println(holder.toString());
        assertEquals("The selected restaurant is Chi's, with average 5 stars reviews and in the Price Category of $$.",holder.toString());
    }

    @Test public void testReviewConstructor(){
        Restaurant holder = new Restaurant("Chi's",5,"$$");
        Review reviewed = new Review("Was very cool and epic","Cristian",2,holder);
        assertEquals("Cristian", reviewed.author);

    }

    @Test public void testReviewToString(){
        Restaurant holder = new Restaurant("Chi's",5,"$$");
        Review reviewed = new Review("Was very cool and epic.","Cristian",2,holder);

        System.out.println(reviewed.toString());

        assertEquals("Hello Cristian, this your review for Chi's. Rated Stars:2 Review:Was very cool and epic.",reviewed.toString());
    }

    @Test public void testUpdateReviewRating(){
        Restaurant holder = new Restaurant("Chi's",0,"$$");
        Review holder2 = null;
        holder.addReview("Was very cool and epic.","Cristian",2);
        holder.addReview("Was very cool .","CristianTwo",4);
        System.out.println(holder.toString());

//        holder2.updateStars("Cristian",2,holder);

        System.out.println(holder.toString());


    }
}
